apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ertony/frontend-ml_project:v1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: url_backend
        - name: CHOKIDAR_USEPOLLING
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: chokidar
