apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cluster
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
