apiVersion: v1
kind: Secret
metadata:
  name: secret-login
  namespace: cluster
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: bWwtcHJvamVjdA==
  MYSQL_USER: ZXJ0b255
  MYSQL_PASSWORD: MTIzNA==
